-- Backfill Supply Officer Mazzu's vendor inventory for databases where
-- CrimsonIsle.sql was applied before the vendor data was added to that file.
SET @VENDOR_ID = (
    SELECT `id`
    FROM `entity`
    WHERE `Creature` = 24491
      AND `World` = 870
      AND `Area` = 1227
    LIMIT 1
);

INSERT INTO `entity_vendor` (`id`, `buyPriceMultiplier`, `sellPriceMultiplier`)
SELECT @VENDOR_ID, 1, 1
FROM DUAL
WHERE @VENDOR_ID IS NOT NULL
ON DUPLICATE KEY UPDATE
    `buyPriceMultiplier` = 1,
    `sellPriceMultiplier` = 1;

DELETE FROM `entity_vendor_category`
WHERE `id` = @VENDOR_ID;

INSERT INTO `entity_vendor_category` (`id`, `index`, `localisedTextId`)
SELECT @VENDOR_ID, 1, 712282 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 2, 712302 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 3, 712312 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 4, 712322 FROM DUAL WHERE @VENDOR_ID IS NOT NULL;

DELETE FROM `entity_vendor_item`
WHERE `id` = @VENDOR_ID;

INSERT INTO `entity_vendor_item` (`id`, `index`, `categoryIndex`, `itemId`)
SELECT @VENDOR_ID, 1, 1, 13179 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 2, 1, 13176 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 3, 1, 13194 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 4, 1, 13188 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 5, 1, 13191 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 6, 1, 13185 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 7, 2, 13148 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 8, 2, 13151 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 9, 2, 13154 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 10, 2, 83720 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 11, 2, 13157 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 12, 2, 83721 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 13, 3, 13160 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 14, 3, 13163 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 15, 3, 13166 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 16, 3, 83722 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 17, 3, 13169 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 18, 3, 83723 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 19, 4, 27873 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 20, 4, 27875 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 21, 4, 27876 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 22, 4, 83724 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 23, 4, 27874 FROM DUAL WHERE @VENDOR_ID IS NOT NULL
UNION ALL
SELECT @VENDOR_ID, 24, 4, 83725 FROM DUAL WHERE @VENDOR_ID IS NOT NULL;
